// types/task.ts
// Task entity types matching backend Task model

/**
 * Task entity representing a todo task belonging to a specific user
 * Mirrors backend Task model from backend/app/models/todo.py
 */
export interface Task {
  /** Unique task identifier (auto-generated by backend) */
  id: number;

  /** Task title (1-1000 characters, required) */
  title: string;

  /** Optional detailed description (max 5000 characters, nullable) */
  description: string | null;

  /** Completion status (default: false) */
  completed: boolean;

  /** User ID who owns this task */
  owner_id: number;

  /** Task creation timestamp (UTC, ISO 8601 format) */
  created_at: string;

  /** Last modification timestamp (UTC, ISO 8601 format) */
  updated_at: string;
}

/**
 * Data submitted when creating a new task
 * Used in task creation form
 */
export interface TaskCreateInput {
  /** Task title (required, 1-1000 characters) */
  title: string;

  /** Optional task description (max 5000 characters) */
  description?: string;
}

/**
 * Data submitted when updating an existing task
 * Used in task edit form
 * Both fields optional (partial updates supported)
 */
export interface TaskUpdateInput {
  /** Updated task title (optional, 1-1000 characters) */
  title?: string;

  /** Updated task description (optional, max 5000 characters) */
  description?: string;
}
